@startuml
title Diagrama de Sequencia referente ao CDU004 - Concluir tarefa

actor Usuário
participant frontend
participant taskController
participant taskRepository
participant taskService

activate Usuário
Usuário -> frontend: Solicitar conclusão de tarefa
activate frontend
frontend -> taskController: PUT /task/{id}/complete
activate taskController
taskController -> taskRepository: findById(id)
activate taskRepository
taskRepository --> taskController: taskData
taskController -> taskRepository: save(existingTask)
deactivate taskRepository
taskController --> frontend: ResponseEntity<Task> OK
deactivate taskController
frontend --> Usuário: Notificar conclusão realizada
deactivate frontend
deactivate Usuário

@enduml
