@startuml
title Diagrama de Sequencia referente ao CDU002 - Criar tarefa

actor Usuário
participant frontend
participant taskController
participant taskRepository
participant task

activate frontend
Usuário -> frontend: Solicitar criação de tarefa
frontend -> taskController: POST /task
activate taskController
taskController -> taskRepository: save(newTask)
activate taskRepository
taskRepository --> task: createdTask
deactivate taskRepository
deactivate task
taskController --> frontend: ResponseEntity<Task> CREATED
deactivate taskController
frontend --> Usuário: Notificar sucesso da criação
deactivate frontend

@enduml
