@startuml
title Diagrama de Sequencia referente ao CDU003 - Excluir tarefa

actor Usuário
participant frontend
participant taskController
participant taskService
participant taskRepository

activate Usuário
Usuário -> frontend: Solicitar exclusão de tarefa
activate frontend
frontend -> taskController: DELETE /task/{id}
activate taskController
taskController -> taskService: deleteTask(id)
activate taskService
taskService -> taskRepository: deleteById(id)
activate taskRepository
taskRepository --> taskService: tarefaExcluida
deactivate taskRepository
deactivate taskService
taskController --> frontend: Tarefa excluída com sucesso
deactivate taskController
frontend --> Usuário: Notificar exclusão realizada
deactivate frontend
deactivate Usuário

@enduml
