@startuml
title Diagrama de Sequencia referente ao CDU001 - Recuperar Tarefas

actor Usuário
participant frontend
participant taskController
participant taskRepository
participant taskService

Usuário -> frontend: Requisitar Tarefas
activate frontend
frontend -> taskController: GET /task
activate taskService
taskController -> taskService: listAll()
activate taskRepository
taskService -> taskRepository: findAll()
taskRepository --> taskService: taskList
deactivate taskRepository
deactivate taskService
taskController --> frontend: ResponseEntity<List<Task>> OK
deactivate taskController
frontend --> Usuário: Exibir Tarefas
deactivate frontend

@enduml
